version: "3.9"
services:
  scraperservice:
    build: .
  cachingservice:
    image: "redis:latest"
    ports: 
        - "6379:6379"
  databaseservice:
    image: "mongo:latest"
    ports:
        - "27017:27017"